# Generated by Django 5.0.6 on 2024-05-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('driver_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=60)),
                ('passport', models.CharField(max_length=10, unique=True)),
                ('driver_licence', models.CharField(max_length=10, unique=True)),
                ('driver_licence_date', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_begin_date', models.DateTimeField()),
                ('order_end_date', models.DateTimeField()),
                ('client_phone_number', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Принят', 'Accepted'), ('Выполняется', 'In Progress'), ('Завершен', 'Done')], max_length=50)),
                ('mark', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('cost', models.FloatField()),
                ('boarding_address', models.CharField(max_length=100)),
                ('destination_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftModel',
            fields=[
                ('shift_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_begin_date', models.DateTimeField(auto_now_add=True)),
                ('shift_end_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('vehicle_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('reg_number', models.CharField(max_length=15, unique=True)),
                ('owner', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddConstraint(
            model_name='drivermodel',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='driver_rating_gte_0_lte_5'),
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.drivermodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.shiftmodel'),
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.vehiclemodel'),
        ),
        migrations.AddConstraint(
            model_name='ordermodel',
            constraint=models.CheckConstraint(check=models.Q(('cost__gt', 0)), name='order_cost_gt_0'),
        ),
    ]
