# Generated by Django 5.0.6 on 2024-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivermodel',
            options={'verbose_name': 'Водители', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='shiftmodel',
            options={'verbose_name': 'Смены', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Транспортные средства', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='driver_code',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Код водителя'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='driver_licence',
            field=models.CharField(max_length=10, unique=True, verbose_name='Водит. удост.'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='driver_licence_date',
            field=models.DateField(verbose_name='Дата выдачи ВУ'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='fio',
            field=models.CharField(max_length=60, verbose_name='ФИО водителя'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='passport',
            field=models.CharField(max_length=10, unique=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='mark',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Принят', 'Accepted'), ('Выполняется', 'In Progress'), ('Завершен', 'Done'), ('Отменен', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='owner',
            field=models.CharField(max_length=60, verbose_name='Собственник ТС'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='reg_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Рег. номер'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_code',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Код трансп. ср-ва'),
        ),
    ]
