# Generated by Django 5.0.6 on 2024-05-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_service', '0002_alter_drivermodel_options_alter_ordermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='mark',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Без оценки'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='shiftmodel',
            name='shift_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
