# Generated by Django 5.0.6 on 2024-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_service', '0003_alter_ordermodel_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmodel',
            name='shift_end_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
