# Generated by Django 5.0.6 on 2024-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_service', '0004_alter_shiftmodel_shift_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmodel',
            name='shift_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
